
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("52dcf6e8-6a23-4e9e-8a82-234e1c1e10c1")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class Database1Entities1
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new Database1Entities1 object using the connection string found in the 'Database1Entities1' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Database1Entities1", "Database1Entities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Database1Entities1 object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Database1Entities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Database1Entities1 object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Database1Entities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Brothers() As ObjectSet(Of Brother)
        Get
            If (_Brothers Is Nothing) Then
                _Brothers = MyBase.CreateObjectSet(Of Brother)("Brothers")
            End If
            Return _Brothers
        End Get
    End Property

    Private _Brothers As ObjectSet(Of Brother)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Canons() As ObjectSet(Of Canon)
        Get
            If (_Canons Is Nothing) Then
                _Canons = MyBase.CreateObjectSet(Of Canon)("Canons")
            End If
            Return _Canons
        End Get
    End Property

    Private _Canons As ObjectSet(Of Canon)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Customers() As ObjectSet(Of Customer)
        Get
            If (_Customers Is Nothing) Then
                _Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
            End If
            Return _Customers
        End Get
    End Property

    Private _Customers As ObjectSet(Of Customer)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ErrrorOfMonths() As ObjectSet(Of ErrrorOfMonth)
        Get
            If (_ErrrorOfMonths Is Nothing) Then
                _ErrrorOfMonths = MyBase.CreateObjectSet(Of ErrrorOfMonth)("ErrrorOfMonths")
            End If
            Return _ErrrorOfMonths
        End Get
    End Property

    Private _ErrrorOfMonths As ObjectSet(Of ErrrorOfMonth)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Fujixeroxes() As ObjectSet(Of Fujixerox)
        Get
            If (_Fujixeroxes Is Nothing) Then
                _Fujixeroxes = MyBase.CreateObjectSet(Of Fujixerox)("Fujixeroxes")
            End If
            Return _Fujixeroxes
        End Get
    End Property

    Private _Fujixeroxes As ObjectSet(Of Fujixerox)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property HondaLocks() As ObjectSet(Of HondaLock)
        Get
            If (_HondaLocks Is Nothing) Then
                _HondaLocks = MyBase.CreateObjectSet(Of HondaLock)("HondaLocks")
            End If
            Return _HondaLocks
        End Get
    End Property

    Private _HondaLocks As ObjectSet(Of HondaLock)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property InformationErrors() As ObjectSet(Of InformationError)
        Get
            If (_InformationErrors Is Nothing) Then
                _InformationErrors = MyBase.CreateObjectSet(Of InformationError)("InformationErrors")
            End If
            Return _InformationErrors
        End Get
    End Property

    Private _InformationErrors As ObjectSet(Of InformationError)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Kyoceras() As ObjectSet(Of Kyocera)
        Get
            If (_Kyoceras Is Nothing) Then
                _Kyoceras = MyBase.CreateObjectSet(Of Kyocera)("Kyoceras")
            End If
            Return _Kyoceras
        End Get
    End Property

    Private _Kyoceras As ObjectSet(Of Kyocera)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property LoiHangNams() As ObjectSet(Of LoiHangNam)
        Get
            If (_LoiHangNams Is Nothing) Then
                _LoiHangNams = MyBase.CreateObjectSet(Of LoiHangNam)("LoiHangNams")
            End If
            Return _LoiHangNams
        End Get
    End Property

    Private _LoiHangNams As ObjectSet(Of LoiHangNam)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property LoiHangThangs() As ObjectSet(Of LoiHangThang)
        Get
            If (_LoiHangThangs Is Nothing) Then
                _LoiHangThangs = MyBase.CreateObjectSet(Of LoiHangThang)("LoiHangThangs")
            End If
            Return _LoiHangThangs
        End Get
    End Property

    Private _LoiHangThangs As ObjectSet(Of LoiHangThang)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Muratas() As ObjectSet(Of Murata)
        Get
            If (_Muratas Is Nothing) Then
                _Muratas = MyBase.CreateObjectSet(Of Murata)("Muratas")
            End If
            Return _Muratas
        End Get
    End Property

    Private _Muratas As ObjectSet(Of Murata)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Nichicons() As ObjectSet(Of Nichicon)
        Get
            If (_Nichicons Is Nothing) Then
                _Nichicons = MyBase.CreateObjectSet(Of Nichicon)("Nichicons")
            End If
            Return _Nichicons
        End Get
    End Property

    Private _Nichicons As ObjectSet(Of Nichicon)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Nihondesans() As ObjectSet(Of Nihondesan)
        Get
            If (_Nihondesans Is Nothing) Then
                _Nihondesans = MyBase.CreateObjectSet(Of Nihondesan)("Nihondesans")
            End If
            Return _Nihondesans
        End Get
    End Property

    Private _Nihondesans As ObjectSet(Of Nihondesan)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Schneiders() As ObjectSet(Of Schneider)
        Get
            If (_Schneiders Is Nothing) Then
                _Schneiders = MyBase.CreateObjectSet(Of Schneider)("Schneiders")
            End If
            Return _Schneiders
        End Get
    End Property

    Private _Schneiders As ObjectSet(Of Schneider)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TOYODENSOes() As ObjectSet(Of TOYODENSO)
        Get
            If (_TOYODENSOes Is Nothing) Then
                _TOYODENSOes = MyBase.CreateObjectSet(Of TOYODENSO)("TOYODENSOes")
            End If
            Return _TOYODENSOes
        End Get
    End Property

    Private _TOYODENSOes As ObjectSet(Of TOYODENSO)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Yokowoes() As ObjectSet(Of Yokowo)
        Get
            If (_Yokowoes Is Nothing) Then
                _Yokowoes = MyBase.CreateObjectSet(Of Yokowo)("Yokowoes")
            End If
            Return _Yokowoes
        End Get
    End Property

    Private _Yokowoes As ObjectSet(Of Yokowo)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Brothers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToBrothers(ByVal brother As Brother)
        MyBase.AddObject("Brothers", brother)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Canons EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCanons(ByVal canon As Canon)
        MyBase.AddObject("Canons", canon)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCustomers(ByVal customer As Customer)
        MyBase.AddObject("Customers", customer)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ErrrorOfMonths EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToErrrorOfMonths(ByVal errrorOfMonth As ErrrorOfMonth)
        MyBase.AddObject("ErrrorOfMonths", errrorOfMonth)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Fujixeroxes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToFujixeroxes(ByVal fujixerox As Fujixerox)
        MyBase.AddObject("Fujixeroxes", fujixerox)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the HondaLocks EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToHondaLocks(ByVal hondaLock As HondaLock)
        MyBase.AddObject("HondaLocks", hondaLock)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the InformationErrors EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToInformationErrors(ByVal informationError As InformationError)
        MyBase.AddObject("InformationErrors", informationError)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Kyoceras EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToKyoceras(ByVal kyocera As Kyocera)
        MyBase.AddObject("Kyoceras", kyocera)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the LoiHangNams EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLoiHangNams(ByVal loiHangNam As LoiHangNam)
        MyBase.AddObject("LoiHangNams", loiHangNam)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the LoiHangThangs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLoiHangThangs(ByVal loiHangThang As LoiHangThang)
        MyBase.AddObject("LoiHangThangs", loiHangThang)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Muratas EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMuratas(ByVal murata As Murata)
        MyBase.AddObject("Muratas", murata)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Nichicons EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToNichicons(ByVal nichicon As Nichicon)
        MyBase.AddObject("Nichicons", nichicon)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Nihondesans EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToNihondesans(ByVal nihondesan As Nihondesan)
        MyBase.AddObject("Nihondesans", nihondesan)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Schneiders EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSchneiders(ByVal schneider As Schneider)
        MyBase.AddObject("Schneiders", schneider)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TOYODENSOes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTOYODENSOes(ByVal tOYODENSO As TOYODENSO)
        MyBase.AddObject("TOYODENSOes", tOYODENSO)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Yokowoes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToYokowoes(ByVal yokowo As Yokowo)
        MyBase.AddObject("Yokowoes", yokowo)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Brother")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Brother
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Brother object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateBrother(dateProduction As Global.System.String) As Brother
        Dim brother as Brother = New Brother
        brother.DateProduction = dateProduction
        Return brother
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Canon")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Canon
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Canon object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateCanon(dateProduction As Global.System.String) As Canon
        Dim canon as Canon = New Canon
        canon.DateProduction = dateProduction
        Return canon
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Customer")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Customer
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Customer object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreateCustomer(id As Global.System.Int32) As Customer
        Dim customer as Customer = New Customer
        customer.ID = id
        Return customer
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NameCustomer() As Global.System.String
        Get
            Return _NameCustomer
        End Get
        Set
            OnNameCustomerChanging(value)
            ReportPropertyChanging("NameCustomer")
            _NameCustomer = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NameCustomer")
            OnNameCustomerChanged()
        End Set
    End Property

    Private _NameCustomer As Global.System.String
    Private Partial Sub OnNameCustomerChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameCustomerChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="ErrrorOfMonth")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ErrrorOfMonth
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ErrrorOfMonth object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateErrrorOfMonth(id As Global.System.Int32) As ErrrorOfMonth
        Dim errrorOfMonth as ErrrorOfMonth = New ErrrorOfMonth
        errrorOfMonth.Id = id
        Return errrorOfMonth
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateOfMonth() As Global.System.String
        Get
            Return _DateOfMonth
        End Get
        Set
            OnDateOfMonthChanging(value)
            ReportPropertyChanging("DateOfMonth")
            _DateOfMonth = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DateOfMonth")
            OnDateOfMonthChanged()
        End Set
    End Property

    Private _DateOfMonth As Global.System.String
    Private Partial Sub OnDateOfMonthChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateOfMonthChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TotalError() As Nullable(Of Global.System.Int32)
        Get
            Return _TotalError
        End Get
        Set
            OnTotalErrorChanging(value)
            ReportPropertyChanging("TotalError")
            _TotalError = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TotalError")
            OnTotalErrorChanged()
        End Set
    End Property

    Private _TotalError As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTotalErrorChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTotalErrorChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Fujixerox")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Fujixerox
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Fujixerox object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateFujixerox(dateProduction As Global.System.String) As Fujixerox
        Dim fujixerox as Fujixerox = New Fujixerox
        fujixerox.DateProduction = dateProduction
        Return fujixerox
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="HondaLock")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class HondaLock
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new HondaLock object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateHondaLock(dateProduction As Global.System.String) As HondaLock
        Dim hondaLock as HondaLock = New HondaLock
        hondaLock.DateProduction = dateProduction
        Return hondaLock
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="InformationError")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class InformationError
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new InformationError object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreateInformationError(id As Global.System.Int32) As InformationError
        Dim informationError as InformationError = New InformationError
        informationError.ID = id
        Return informationError
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            OnDateProductionChanging(value)
            ReportPropertyChanging("DateProduction")
            _DateProduction = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DateProduction")
            OnDateProductionChanged()
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DayShift() As Nullable(Of Global.System.Boolean)
        Get
            Return _DayShift
        End Get
        Set
            OnDayShiftChanging(value)
            ReportPropertyChanging("DayShift")
            _DayShift = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DayShift")
            OnDayShiftChanged()
        End Set
    End Property

    Private _DayShift As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnDayShiftChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnDayShiftChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorToyodenso() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorToyodenso
        End Get
        Set
            OnDateErrorToyodensoChanging(value)
            ReportPropertyChanging("DateErrorToyodenso")
            _DateErrorToyodenso = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorToyodenso")
            OnDateErrorToyodensoChanged()
        End Set
    End Property

    Private _DateErrorToyodenso As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorToyodensoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorToyodensoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorHondaLock() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorHondaLock
        End Get
        Set
            OnDateErrorHondaLockChanging(value)
            ReportPropertyChanging("DateErrorHondaLock")
            _DateErrorHondaLock = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorHondaLock")
            OnDateErrorHondaLockChanged()
        End Set
    End Property

    Private _DateErrorHondaLock As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorHondaLockChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorHondaLockChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorYokowo() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorYokowo
        End Get
        Set
            OnDateErrorYokowoChanging(value)
            ReportPropertyChanging("DateErrorYokowo")
            _DateErrorYokowo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorYokowo")
            OnDateErrorYokowoChanged()
        End Set
    End Property

    Private _DateErrorYokowo As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorYokowoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorYokowoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorNihondesan() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorNihondesan
        End Get
        Set
            OnDateErrorNihondesanChanging(value)
            ReportPropertyChanging("DateErrorNihondesan")
            _DateErrorNihondesan = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorNihondesan")
            OnDateErrorNihondesanChanged()
        End Set
    End Property

    Private _DateErrorNihondesan As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorNihondesanChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorNihondesanChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorCanon() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorCanon
        End Get
        Set
            OnDateErrorCanonChanging(value)
            ReportPropertyChanging("DateErrorCanon")
            _DateErrorCanon = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorCanon")
            OnDateErrorCanonChanged()
        End Set
    End Property

    Private _DateErrorCanon As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorCanonChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorCanonChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorBrother() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorBrother
        End Get
        Set
            OnDateErrorBrotherChanging(value)
            ReportPropertyChanging("DateErrorBrother")
            _DateErrorBrother = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorBrother")
            OnDateErrorBrotherChanged()
        End Set
    End Property

    Private _DateErrorBrother As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorBrotherChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorBrotherChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorMurata() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorMurata
        End Get
        Set
            OnDateErrorMurataChanging(value)
            ReportPropertyChanging("DateErrorMurata")
            _DateErrorMurata = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorMurata")
            OnDateErrorMurataChanged()
        End Set
    End Property

    Private _DateErrorMurata As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorMurataChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorMurataChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorSchneider() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorSchneider
        End Get
        Set
            OnDateErrorSchneiderChanging(value)
            ReportPropertyChanging("DateErrorSchneider")
            _DateErrorSchneider = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorSchneider")
            OnDateErrorSchneiderChanged()
        End Set
    End Property

    Private _DateErrorSchneider As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorSchneiderChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorSchneiderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorKyocera() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorKyocera
        End Get
        Set
            OnDateErrorKyoceraChanging(value)
            ReportPropertyChanging("DateErrorKyocera")
            _DateErrorKyocera = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorKyocera")
            OnDateErrorKyoceraChanged()
        End Set
    End Property

    Private _DateErrorKyocera As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorKyoceraChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorKyoceraChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorFujixerox() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorFujixerox
        End Get
        Set
            OnDateErrorFujixeroxChanging(value)
            ReportPropertyChanging("DateErrorFujixerox")
            _DateErrorFujixerox = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorFujixerox")
            OnDateErrorFujixeroxChanged()
        End Set
    End Property

    Private _DateErrorFujixerox As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorFujixeroxChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorFujixeroxChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateErrorNichicon() As Nullable(Of Global.System.Int32)
        Get
            Return _DateErrorNichicon
        End Get
        Set
            OnDateErrorNichiconChanging(value)
            ReportPropertyChanging("DateErrorNichicon")
            _DateErrorNichicon = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateErrorNichicon")
            OnDateErrorNichiconChanged()
        End Set
    End Property

    Private _DateErrorNichicon As Nullable(Of Global.System.Int32)
    Private Partial Sub OnDateErrorNichiconChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnDateErrorNichiconChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Kyocera")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Kyocera
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Kyocera object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateKyocera(dateProduction As Global.System.String) As Kyocera
        Dim kyocera as Kyocera = New Kyocera
        kyocera.DateProduction = dateProduction
        Return kyocera
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="LoiHangNam")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class LoiHangNam
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new LoiHangNam object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    Public Shared Function CreateLoiHangNam(id As Global.System.Int32) As LoiHangNam
        Dim loiHangNam as LoiHangNam = New LoiHangNam
        loiHangNam.Id = id
        Return loiHangNam
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Nam() As Global.System.String
        Get
            Return _Nam
        End Get
        Set
            OnNamChanging(value)
            ReportPropertyChanging("Nam")
            _Nam = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Nam")
            OnNamChanged()
        End Set
    End Property

    Private _Nam As Global.System.String
    Private Partial Sub OnNamChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNamChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T1() As Nullable(Of Global.System.Int32)
        Get
            Return _T1
        End Get
        Set
            OnT1Changing(value)
            ReportPropertyChanging("T1")
            _T1 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T1")
            OnT1Changed()
        End Set
    End Property

    Private _T1 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT1Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T2() As Nullable(Of Global.System.Int32)
        Get
            Return _T2
        End Get
        Set
            OnT2Changing(value)
            ReportPropertyChanging("T2")
            _T2 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T2")
            OnT2Changed()
        End Set
    End Property

    Private _T2 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT2Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T3() As Nullable(Of Global.System.Int32)
        Get
            Return _T3
        End Get
        Set
            OnT3Changing(value)
            ReportPropertyChanging("T3")
            _T3 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T3")
            OnT3Changed()
        End Set
    End Property

    Private _T3 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT3Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT3Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T4() As Nullable(Of Global.System.Int32)
        Get
            Return _T4
        End Get
        Set
            OnT4Changing(value)
            ReportPropertyChanging("T4")
            _T4 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T4")
            OnT4Changed()
        End Set
    End Property

    Private _T4 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT4Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT4Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T5() As Nullable(Of Global.System.Int32)
        Get
            Return _T5
        End Get
        Set
            OnT5Changing(value)
            ReportPropertyChanging("T5")
            _T5 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T5")
            OnT5Changed()
        End Set
    End Property

    Private _T5 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT5Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT5Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T6() As Nullable(Of Global.System.Int32)
        Get
            Return _T6
        End Get
        Set
            OnT6Changing(value)
            ReportPropertyChanging("T6")
            _T6 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T6")
            OnT6Changed()
        End Set
    End Property

    Private _T6 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT6Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT6Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T7() As Nullable(Of Global.System.Int32)
        Get
            Return _T7
        End Get
        Set
            OnT7Changing(value)
            ReportPropertyChanging("T7")
            _T7 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T7")
            OnT7Changed()
        End Set
    End Property

    Private _T7 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT7Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT7Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T8() As Nullable(Of Global.System.Int32)
        Get
            Return _T8
        End Get
        Set
            OnT8Changing(value)
            ReportPropertyChanging("T8")
            _T8 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T8")
            OnT8Changed()
        End Set
    End Property

    Private _T8 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT8Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT8Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T9() As Nullable(Of Global.System.Int32)
        Get
            Return _T9
        End Get
        Set
            OnT9Changing(value)
            ReportPropertyChanging("T9")
            _T9 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T9")
            OnT9Changed()
        End Set
    End Property

    Private _T9 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT9Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT9Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T10() As Nullable(Of Global.System.Int32)
        Get
            Return _T10
        End Get
        Set
            OnT10Changing(value)
            ReportPropertyChanging("T10")
            _T10 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T10")
            OnT10Changed()
        End Set
    End Property

    Private _T10 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT10Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT10Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T11() As Nullable(Of Global.System.Int32)
        Get
            Return _T11
        End Get
        Set
            OnT11Changing(value)
            ReportPropertyChanging("T11")
            _T11 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T11")
            OnT11Changed()
        End Set
    End Property

    Private _T11 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT11Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT11Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property T12() As Nullable(Of Global.System.Int32)
        Get
            Return _T12
        End Get
        Set
            OnT12Changing(value)
            ReportPropertyChanging("T12")
            _T12 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("T12")
            OnT12Changed()
        End Set
    End Property

    Private _T12 As Nullable(Of Global.System.Int32)
    Private Partial Sub OnT12Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnT12Changed()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="LoiHangThang")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class LoiHangThang
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new LoiHangThang object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    Public Shared Function CreateLoiHangThang(id As Global.System.Int32) As LoiHangThang
        Dim loiHangThang as LoiHangThang = New LoiHangThang
        loiHangThang.ID = id
        Return loiHangThang
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NamThang() As Global.System.String
        Get
            Return _NamThang
        End Get
        Set
            OnNamThangChanging(value)
            ReportPropertyChanging("NamThang")
            _NamThang = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NamThang")
            OnNamThangChanged()
        End Set
    End Property

    Private _NamThang As Global.System.String
    Private Partial Sub OnNamThangChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNamThangChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TotalError() As Nullable(Of Global.System.Int32)
        Get
            Return _TotalError
        End Get
        Set
            OnTotalErrorChanging(value)
            ReportPropertyChanging("TotalError")
            _TotalError = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TotalError")
            OnTotalErrorChanged()
        End Set
    End Property

    Private _TotalError As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTotalErrorChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTotalErrorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorToyodenso() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorToyodenso
        End Get
        Set
            OnErrorToyodensoChanging(value)
            ReportPropertyChanging("ErrorToyodenso")
            _ErrorToyodenso = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorToyodenso")
            OnErrorToyodensoChanged()
        End Set
    End Property

    Private _ErrorToyodenso As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorToyodensoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorToyodensoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorHondaLock() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorHondaLock
        End Get
        Set
            OnErrorHondaLockChanging(value)
            ReportPropertyChanging("ErrorHondaLock")
            _ErrorHondaLock = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorHondaLock")
            OnErrorHondaLockChanged()
        End Set
    End Property

    Private _ErrorHondaLock As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorHondaLockChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorHondaLockChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorYokowo() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorYokowo
        End Get
        Set
            OnErrorYokowoChanging(value)
            ReportPropertyChanging("ErrorYokowo")
            _ErrorYokowo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorYokowo")
            OnErrorYokowoChanged()
        End Set
    End Property

    Private _ErrorYokowo As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorYokowoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorYokowoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorNihondesan() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorNihondesan
        End Get
        Set
            OnErrorNihondesanChanging(value)
            ReportPropertyChanging("ErrorNihondesan")
            _ErrorNihondesan = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorNihondesan")
            OnErrorNihondesanChanged()
        End Set
    End Property

    Private _ErrorNihondesan As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorNihondesanChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorNihondesanChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorCanon() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorCanon
        End Get
        Set
            OnErrorCanonChanging(value)
            ReportPropertyChanging("ErrorCanon")
            _ErrorCanon = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorCanon")
            OnErrorCanonChanged()
        End Set
    End Property

    Private _ErrorCanon As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorCanonChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorCanonChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorBrother() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorBrother
        End Get
        Set
            OnErrorBrotherChanging(value)
            ReportPropertyChanging("ErrorBrother")
            _ErrorBrother = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorBrother")
            OnErrorBrotherChanged()
        End Set
    End Property

    Private _ErrorBrother As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorBrotherChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorBrotherChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorMurata() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorMurata
        End Get
        Set
            OnErrorMurataChanging(value)
            ReportPropertyChanging("ErrorMurata")
            _ErrorMurata = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorMurata")
            OnErrorMurataChanged()
        End Set
    End Property

    Private _ErrorMurata As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorMurataChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorMurataChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorSchneider() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorSchneider
        End Get
        Set
            OnErrorSchneiderChanging(value)
            ReportPropertyChanging("ErrorSchneider")
            _ErrorSchneider = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorSchneider")
            OnErrorSchneiderChanged()
        End Set
    End Property

    Private _ErrorSchneider As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorSchneiderChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorSchneiderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorKyocera() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorKyocera
        End Get
        Set
            OnErrorKyoceraChanging(value)
            ReportPropertyChanging("ErrorKyocera")
            _ErrorKyocera = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorKyocera")
            OnErrorKyoceraChanged()
        End Set
    End Property

    Private _ErrorKyocera As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorKyoceraChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorKyoceraChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorFujixerox() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorFujixerox
        End Get
        Set
            OnErrorFujixeroxChanging(value)
            ReportPropertyChanging("ErrorFujixerox")
            _ErrorFujixerox = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorFujixerox")
            OnErrorFujixeroxChanged()
        End Set
    End Property

    Private _ErrorFujixerox As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorFujixeroxChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorFujixeroxChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorNichicon() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorNichicon
        End Get
        Set
            OnErrorNichiconChanging(value)
            ReportPropertyChanging("ErrorNichicon")
            _ErrorNichicon = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorNichicon")
            OnErrorNichiconChanged()
        End Set
    End Property

    Private _ErrorNichicon As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorNichiconChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorNichiconChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Murata")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Murata
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Murata object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateMurata(dateProduction As Global.System.String) As Murata
        Dim murata as Murata = New Murata
        murata.DateProduction = dateProduction
        Return murata
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Nichicon")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Nichicon
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Nichicon object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateNichicon(dateProduction As Global.System.String) As Nichicon
        Dim nichicon as Nichicon = New Nichicon
        nichicon.DateProduction = dateProduction
        Return nichicon
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Nihondesan")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Nihondesan
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Nihondesan object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateNihondesan(dateProduction As Global.System.String) As Nihondesan
        Dim nihondesan as Nihondesan = New Nihondesan
        nihondesan.DateProduction = dateProduction
        Return nihondesan
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Schneider")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Schneider
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Schneider object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateSchneider(dateProduction As Global.System.String) As Schneider
        Dim schneider as Schneider = New Schneider
        schneider.DateProduction = dateProduction
        Return schneider
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="TOYODENSO")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TOYODENSO
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TOYODENSO object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateTOYODENSO(dateProduction As Global.System.String) As TOYODENSO
        Dim tOYODENSO as TOYODENSO = New TOYODENSO
        tOYODENSO.DateProduction = dateProduction
        Return tOYODENSO
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database1Model", Name:="Yokowo")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Yokowo
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Yokowo object.
    ''' </summary>
    ''' <param name="dateProduction">Initial value of the DateProduction property.</param>
    Public Shared Function CreateYokowo(dateProduction As Global.System.String) As Yokowo
        Dim yokowo as Yokowo = New Yokowo
        yokowo.DateProduction = dateProduction
        Return yokowo
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateProduction() As Global.System.String
        Get
            Return _DateProduction
        End Get
        Set
            If (_DateProduction <> Value) Then
                OnDateProductionChanging(value)
                ReportPropertyChanging("DateProduction")
                _DateProduction = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DateProduction")
                OnDateProductionChanged()
            End If
        End Set
    End Property

    Private _DateProduction As Global.System.String
    Private Partial Sub OnDateProductionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateProductionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ErrorTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _ErrorTotal
        End Get
        Set
            OnErrorTotalChanging(value)
            ReportPropertyChanging("ErrorTotal")
            _ErrorTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ErrorTotal")
            OnErrorTotalChanged()
        End Set
    End Property

    Private _ErrorTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnErrorTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnErrorTotalChanged()
    End Sub

    #End Region

End Class

#End Region


